"""Reliability/verification agent.

Independently judges whether a test produced by the test-maintenance agent
is trustworthy — never by reading alone, always by actually executing it —
and checks a lightweight EU AI Act Article 50 transparency obligation: an
AI-generated test must be disclosed as such, not indistinguishable from a
human-written one.
"""

import ast
import subprocess
import sys
from pathlib import Path

from ..exclusions import is_excluded
from .contracts import AgentReport

AI_DISCLOSURE_MARKERS = (
    "ai-generated",
    "ai generated",
    "generated by ai-test-tool",
)

# Substrings in pytest output that indicate the test references code that
# doesn't actually exist — a strong sign of hallucination rather than a
# legitimate assertion failure.
HALLUCINATION_MARKERS = (
    "ModuleNotFoundError",
    "ImportError",
    "AttributeError",
    "NameError",
    "has no attribute",
)

_CLASSIFICATION_PRIORITY = {"not_reliable": 2, "needs_improvement": 1, "reliable": 0}


def run(target: str, stage: str = "pre-commit", **context) -> dict:
    target_path = Path(target).resolve()
    test_paths = _resolve_test_paths(target_path, context)

    if not test_paths:
        return AgentReport(
            agent="reliability",
            stage=stage,
            summary="No generated test found to verify",
            passed=True,
        ).to_dict()

    file_results = [_verify_single_test(target_path, path) for path in test_paths]

    if len(file_results) == 1:
        details = dict(file_results[0])
        details["files"] = file_results
        summary = f"{_classification_label(details['classification'])} — {Path(details['test_path']).name}"
        passed = details["classification"] == "reliable" and details["is_compliant"]
    else:
        details = _aggregate(file_results)
        reliable_count = sum(1 for f in file_results if f["classification"] == "reliable")
        summary = f"{reliable_count}/{len(file_results)} tests reliable"
        passed = details["classification"] == "reliable" and details["is_compliant"]

    report = AgentReport(
        agent="reliability",
        stage=stage,
        summary=summary,
        passed=passed,
        details=details,
    )
    return report.to_dict()


def _verify_single_test(target_path: Path, test_path: Path) -> dict:
    executed, test_passed, output = _execute_test(target_path, test_path)
    meaningfulness_tier, meaningfulness_notes = _check_meaningfulness(test_path)
    is_compliant, compliance_notes = _check_ai_disclosure(test_path)
    is_hallucinated, hallucination_notes = _check_hallucination(test_passed, output)

    classification = _classify(executed, test_passed, meaningfulness_tier, is_hallucinated)
    notes = "; ".join(
        n for n in (hallucination_notes, meaningfulness_notes, compliance_notes) if n
    )

    return {
        "test_path": str(_relative_or_absolute(test_path, target_path)),
        "executed": executed,
        "test_passed": test_passed,
        "is_meaningful": meaningfulness_tier != "none",
        "is_hallucinated": is_hallucinated,
        "classification": classification,
        "is_compliant": is_compliant,
        "notes": notes,
    }


def _aggregate(file_results: list[dict]) -> dict:
    worst = max(file_results, key=lambda f: _CLASSIFICATION_PRIORITY[f["classification"]])
    return {
        "classification": worst["classification"],
        "is_compliant": all(f["is_compliant"] for f in file_results),
        "is_hallucinated": any(f["is_hallucinated"] for f in file_results),
        "notes": worst["notes"],
        "files": file_results,
    }


def _resolve_test_paths(target_path: Path, context: dict) -> list[Path]:
    """Figure out which test file(s) to verify.

    Prefers an explicit `test_path` in context, then any
    `generated_test_path`(s) from test-maintenance results earlier in the
    same dispatch, then falls back to whatever test file(s) are actually
    staged for this commit — every one of them, not just the newest, since
    a single commit can introduce or update more than one test.

    Deliberately does NOT fall back to "newest test file anywhere in the
    repo" — that would make this agent grade unrelated, pre-existing files
    on every commit/push, blocking work that has nothing to do with a
    freshly generated test. If none of the above apply, there is genuinely
    nothing for this agent to check yet, and it should no-op rather than
    guess.
    """
    explicit = context.get("test_path")
    if explicit:
        return [(target_path / explicit).resolve()]

    generated_from_upstream = []
    for result in context.get("upstream_results") or []:
        if result.get("agent") != "test-maintenance":
            continue
        details = result.get("details", {})
        generated = details.get("generated_test_path")
        if generated:
            generated_from_upstream.append((target_path / generated).resolve())
        for path_str in details.get("generated_test_paths") or []:
            generated_from_upstream.append((target_path / path_str).resolve())
    if generated_from_upstream:
        return generated_from_upstream

    return _staged_test_files(target_path)


def _staged_test_files(target_path: Path) -> list[Path]:
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            cwd=target_path,
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []

    matches = []
    for line in result.stdout.splitlines():
        candidate = target_path / line.strip()
        if candidate.suffix != ".py" or not candidate.name.startswith("test_"):
            continue
        if is_excluded(candidate):
            continue
        if candidate.exists():
            matches.append(candidate)
    return matches


def _execute_test(target_path: Path, test_path: Path) -> tuple[bool, bool, str]:
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", str(test_path)],
        cwd=target_path,
        capture_output=True,
        text=True,
    )
    # 0 = all passed, 1 = ran but some failed — both mean it actually executed.
    executed = result.returncode in (0, 1)
    test_passed = result.returncode == 0
    return executed, test_passed, result.stdout + result.stderr


def _check_meaningfulness(test_path: Path) -> tuple[str, str]:
    """Returns a tier ("strong", "weak", "none") and an explanatory note."""
    try:
        tree = ast.parse(test_path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return "none", "Could not parse test file"

    assert_count = 0
    trivial_count = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Assert):
            assert_count += 1
            if _is_trivial_assert(node):
                trivial_count += 1

    if assert_count == 0:
        return "none", "Test contains no assertions"
    if trivial_count == assert_count:
        return "none", "All assertions are trivially true and cannot fail"
    if trivial_count > 0:
        return "weak", f"{trivial_count} of {assert_count} assertions look trivial"
    return "strong", ""


def _is_trivial_assert(node: ast.Assert) -> bool:
    test = node.test
    if isinstance(test, ast.Constant) and test.value is True:
        return True
    if isinstance(test, ast.Compare) and test.comparators:
        left, right = test.left, test.comparators[0]
        if isinstance(left, ast.Constant) and isinstance(right, ast.Constant):
            return ast.dump(left) == ast.dump(right)
    return False


def _check_ai_disclosure(test_path: Path) -> tuple[bool, str]:
    """EU AI Act, Article 50: AI-generated content must be disclosed as such.

    We check for a simple marker near the top of the file rather than
    assuming compliance — absence of a marker is treated as non-compliant,
    not as "presumably human-written."
    """
    try:
        head = test_path.read_text(encoding="utf-8")[:500].lower()
    except (OSError, UnicodeDecodeError):
        return False, "Could not read file to check AI-disclosure marker"

    if any(marker in head for marker in AI_DISCLOSURE_MARKERS):
        return True, ""
    return False, "Missing AI-generated disclosure marker (EU AI Act Art. 50)"


def _check_hallucination(test_passed: bool, output: str) -> tuple[bool, str]:
    """Distinguish a genuine assertion failure from a test that references
    code that doesn't actually exist (hallucinated functions/attributes).

    Only meaningful when the test failed to begin with — a passing test
    isn't hallucinated, even if it happens to mention these words.
    """
    if test_passed:
        return False, ""
    for marker in HALLUCINATION_MARKERS:
        if marker in output:
            return True, f"References code that doesn't exist ({marker} in output)"
    return False, ""


def _classify(
    executed: bool, test_passed: bool, meaningfulness_tier: str, is_hallucinated: bool
) -> str:
    if is_hallucinated:
        return "not_reliable"
    if not executed or not test_passed:
        return "not_reliable"
    if meaningfulness_tier == "none":
        return "not_reliable"
    if meaningfulness_tier == "weak":
        return "needs_improvement"
    return "reliable"


def _classification_label(classification: str) -> str:
    return {
        "reliable": "Reliable",
        "needs_improvement": "Needs improvement",
        "not_reliable": "Not reliable",
    }[classification]


def _relative_or_absolute(test_path: Path, target_path: Path) -> Path:
    try:
        return test_path.relative_to(target_path)
    except ValueError:
        return test_path
