from datetime import date

import pytest

from app.trip_logic import is_day_within_trip, trip_duration_days, trips_overlap


def test_trip_duration_days_single_day():
    d = date(2026, 1, 1)
    assert trip_duration_days(d, d) == 1


def test_trip_duration_days_multi_day():
    assert trip_duration_days(date(2026, 1, 1), date(2026, 1, 5)) == 5


def test_trip_duration_days_raises_when_end_before_start():
    with pytest.raises(ValueError):
        trip_duration_days(date(2026, 1, 5), date(2026, 1, 1))


def test_is_day_within_trip_true_for_a_day_inside_range():
    assert is_day_within_trip(date(2026, 1, 3), date(2026, 1, 1), date(2026, 1, 5))


# AI-generated by ai-test-tool
# Tests for trips_overlap function
def test_trips_overlap_same_trip():
    """Two identical trips should overlap."""
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 5), date(2026, 1, 1), date(2026, 1, 5)) is True


def test_trips_overlap_complete_overlap():
    """Trip A completely overlaps Trip B."""
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 10), date(2026, 1, 3), date(2026, 1, 7)) is True


def test_trips_overlap_partial_overlap_start():
    """Trip B starts during Trip A."""
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 5), date(2026, 1, 3), date(2026, 1, 7)) is True


def test_trips_overlap_partial_overlap_end():
    """Trip A starts during Trip B."""
    assert trips_overlap(date(2026, 1, 3), date(2026, 1, 7), date(2026, 1, 1), date(2026, 1, 5)) is True


def test_trips_overlap_no_overlap_before():
    """Trip A ends before Trip B starts."""
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 3), date(2026, 1, 5), date(2026, 1, 7)) is False


def test_trips_overlap_no_overlap_after():
    """Trip A starts after Trip B ends."""
    assert trips_overlap(date(2026, 1, 5), date(2026, 1, 7), date(2026, 1, 1), date(2026, 1, 3)) is False


def test_trips_overlap_touch_at_endpoints():
    """Trips that touch at exact endpoints should overlap."""
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 5), date(2026, 1, 5), date(2026, 1, 7)) is True


def test_trips_overlap_one_contains_other():
    """Trip A contains Trip B entirely."""
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 10), date(2026, 1, 2), date(2026, 1, 3)) is True
