import subprocess
from pathlib import Path

from ai_test_tool.agents import reliability


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def test_run_reports_none_when_nothing_to_check(tmp_path: Path):
    result = reliability.run(target=str(tmp_path), stage="pre-commit")

    assert result["summary"] == "No generated test found to verify"
    assert result["passed"] is True


def test_run_does_not_pick_up_unrelated_pre_existing_test_files(tmp_path: Path):
    """Regression test: reliability must never grade a random file that
    happens to exist in the repo but isn't part of the current change —
    doing so previously blocked every unrelated commit/push."""
    _write(
        tmp_path / "test_unrelated.py",
        "def test_unrelated():\n    assert True\n",
    )

    result = reliability.run(target=str(tmp_path), stage="pre-commit")

    assert result["summary"] == "No generated test found to verify"
    assert result["passed"] is True


def test_meaningful_passing_disclosed_test_is_reliable_and_compliant(tmp_path: Path):
    test_file = tmp_path / "test_add.py"
    _write(
        test_file,
        "# AI-generated by ai-test-tool\n"
        "def add(a, b):\n"
        "    return a + b\n\n"
        "def test_add():\n"
        "    assert add(2, 3) == 5\n",
    )

    result = reliability.run(target=str(tmp_path), stage="pre-commit", test_path="test_add.py")
    details = result["details"]

    assert details["classification"] == "reliable"
    assert details["is_compliant"] is True
    assert result["passed"] is True


def test_trivial_assertion_is_classified_not_reliable(tmp_path: Path):
    _write(
        tmp_path / "test_trivial.py",
        "# AI-generated by ai-test-tool\n"
        "def test_trivial():\n"
        "    assert True\n",
    )

    result = reliability.run(target=str(tmp_path), stage="pre-commit", test_path="test_trivial.py")
    details = result["details"]

    assert details["classification"] == "not_reliable"
    assert result["passed"] is False


def test_failing_test_is_classified_not_reliable(tmp_path: Path):
    _write(
        tmp_path / "test_broken.py",
        "# AI-generated by ai-test-tool\n"
        "def test_broken():\n"
        "    assert 1 == 2\n",
    )

    result = reliability.run(target=str(tmp_path), stage="pre-commit", test_path="test_broken.py")
    details = result["details"]

    assert details["executed"] is True
    assert details["test_passed"] is False
    assert details["classification"] == "not_reliable"


def test_missing_ai_disclosure_marker_is_flagged_non_compliant(tmp_path: Path):
    _write(
        tmp_path / "test_no_marker.py",
        "def test_no_marker():\n    assert 2 + 2 == 4\n",
    )

    result = reliability.run(target=str(tmp_path), stage="pre-commit", test_path="test_no_marker.py")
    details = result["details"]

    assert details["classification"] == "reliable"
    assert details["is_compliant"] is False
    assert "EU AI Act" in details["notes"]
    # Reliable but undisclosed should still fail the overall gate.
    assert result["passed"] is False


def test_run_prefers_generated_test_path_from_upstream_results(tmp_path: Path):
    (tmp_path / "tests").mkdir()
    _write(
        tmp_path / "tests" / "test_target.py",
        "# AI-generated by ai-test-tool\n"
        "def test_target():\n"
        "    assert 1 + 1 == 2\n",
    )
    _write(
        tmp_path / "test_decoy.py",
        "# AI-generated by ai-test-tool\n"
        "def test_decoy():\n"
        "    assert False\n",
    )

    upstream_results = [
        {
            "agent": "test-maintenance",
            "stage": "pre-commit",
            "summary": "generated 1 test",
            "details": {"generated_test_path": "tests/test_target.py"},
        }
    ]

    result = reliability.run(
        target=str(tmp_path), stage="pre-commit", upstream_results=upstream_results
    )

    assert result["details"]["test_path"] in ("tests/test_target.py", "tests\\test_target.py")
    assert result["details"]["classification"] == "reliable"


def test_run_picks_up_staged_test_file_automatically(tmp_path: Path):
    """When no explicit path/upstream result is given, fall back to
    whatever test file is actually staged for commit — never an
    unrelated pre-existing one."""
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo, check=True)

    # An old, already-committed test file — must NOT be picked up.
    _write(repo / "test_old.py", "def test_old():\n    assert True\n")
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "old"], cwd=repo, check=True)

    # A newly staged test file — this one SHOULD be picked up.
    _write(
        repo / "test_new.py",
        "# AI-generated by ai-test-tool\n"
        "def test_new():\n"
        "    assert 3 * 3 == 9\n",
    )
    subprocess.run(["git", "add", "test_new.py"], cwd=repo, check=True)

    result = reliability.run(target=str(repo), stage="pre-commit")

    assert result["details"]["test_path"] in ("test_new.py",)
    assert result["details"]["classification"] == "reliable"
