"""End-to-end integration tests combining the orchestrator with the real
test-maintenance and reliability agents together — not just each agent in
isolation. This is the actual chain a `pre-commit` hook runs, and it's the
core thing the project needs to demonstrate: that a bad AI-generated test
gets caught before it's trusted, and a good one is correctly approved.
"""

import subprocess
from pathlib import Path

from ai_test_tool import ai_client, orchestrator
from ai_test_tool.agents import reliability, test_maintenance

GENERATED_TRIPS_OVERLAP_TEST = '''def test_trips_overlap_true_for_touching_ranges():
    from datetime import date
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 5), date(2026, 1, 5), date(2026, 1, 7))


def test_trips_overlap_false_for_disjoint_ranges():
    from datetime import date
    assert not trips_overlap(date(2026, 1, 1), date(2026, 1, 2), date(2026, 1, 5), date(2026, 1, 7))
'''

TRIP_LOGIC_SOURCE = '''
from datetime import date


def trip_duration_days(start_date: date, end_date: date) -> int:
    return (end_date - start_date).days + 1


def is_day_within_trip(day: date, start_date: date, end_date: date) -> bool:
    return start_date <= day <= end_date


def trips_overlap(start_a: date, end_a: date, start_b: date, end_b: date) -> bool:
    return start_a <= end_b and start_b <= end_a
'''

EXISTING_TEST_SOURCE = '''
from datetime import date

import pytest

from app.trip_logic import is_day_within_trip, trip_duration_days


def test_trip_duration_days_single_day():
    d = date(2026, 1, 1)
    assert trip_duration_days(d, d) == 1


def test_is_day_within_trip_true_for_a_day_inside_range():
    assert is_day_within_trip(date(2026, 1, 3), date(2026, 1, 1), date(2026, 1, 5))
'''


def _seed_repo(tmp_path: Path) -> Path:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=tmp_path, check=True)
    (tmp_path / "app").mkdir()
    (tmp_path / "app" / "__init__.py").write_text("", encoding="utf-8")
    trip_logic = tmp_path / "app" / "trip_logic.py"
    trip_logic.write_text(TRIP_LOGIC_SOURCE, encoding="utf-8")
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "__init__.py").write_text("", encoding="utf-8")
    (tmp_path / "tests" / "test_trip_logic.py").write_text(EXISTING_TEST_SOURCE, encoding="utf-8")
    subprocess.run(["git", "add", str(trip_logic)], cwd=tmp_path, check=True)
    return tmp_path


def test_full_pre_commit_chain_approves_a_genuinely_good_generated_test(tmp_path: Path, monkeypatch):
    _seed_repo(tmp_path)
    monkeypatch.setattr(ai_client, "generate", lambda prompt, **k: GENERATED_TRIPS_OVERLAP_TEST)
    orchestrator.register("pre-commit", test_maintenance.run)
    orchestrator.register("pre-commit", reliability.run)

    results = orchestrator.dispatch("pre-commit", target=str(tmp_path))

    assert len(results) == 2
    tm_result, rel_result = results

    assert tm_result["agent"] == "test-maintenance"
    assert {g["function"] for g in tm_result["details"]["generated"]} == {"trips_overlap"}

    assert rel_result["agent"] == "reliability"
    assert rel_result["details"]["classification"] == "reliable"
    assert rel_result["details"]["is_compliant"] is True
    assert rel_result["passed"] is True

    failed = any(r.get("passed") is False for r in results)
    assert failed is False


def test_full_pre_commit_chain_blocks_a_hallucinated_generated_test(tmp_path: Path):
    """Stands in for test-maintenance with a deliberately broken agent (not
    the real one) to prove reliability actually catches bad AI output when
    it's wired into the real dispatch chain, not just in isolation."""
    _seed_repo(tmp_path)

    def fake_broken_test_maintenance(target, stage, **context):
        test_path = Path(target) / "tests" / "test_hallucinated.py"
        test_path.write_text(
            "# AI-generated by ai-test-tool\n"
            "from app.trip_logic import totally_made_up_function\n\n"
            "def test_hallucinated():\n"
            "    assert totally_made_up_function() == 42\n",
            encoding="utf-8",
        )
        return {
            "agent": "test-maintenance",
            "stage": stage,
            "summary": "Generated tests for a function that doesn't exist",
            "passed": True,
            "details": {
                "file": "app/trip_logic.py",
                "function": "totally_made_up_function",
                "generated_test_path": "tests/test_hallucinated.py",
                "status": "generated",
            },
        }

    orchestrator.register("pre-commit", fake_broken_test_maintenance)
    orchestrator.register("pre-commit", reliability.run)

    results = orchestrator.dispatch("pre-commit", target=str(tmp_path))

    rel_result = results[1]
    assert rel_result["details"]["classification"] == "not_reliable"
    assert rel_result["details"]["is_hallucinated"] is True
    assert rel_result["passed"] is False

    # This is what cli.py checks to decide whether to block the commit.
    failed = any(r.get("passed") is False for r in results)
    assert failed is True


def test_full_pre_commit_chain_blocks_an_undisclosed_generated_test(tmp_path: Path):
    """A test can be perfectly reliable and still fail the gate if it isn't
    disclosed as AI-generated (EU AI Act, Article 50)."""
    _seed_repo(tmp_path)

    def fake_undisclosed_test_maintenance(target, stage, **context):
        test_path = Path(target) / "tests" / "test_undisclosed.py"
        test_path.write_text(
            "def test_undisclosed():\n    assert 2 + 2 == 4\n",
            encoding="utf-8",
        )
        return {
            "agent": "test-maintenance",
            "stage": stage,
            "summary": "Generated a test without a disclosure marker",
            "passed": True,
            "details": {
                "file": "app/trip_logic.py",
                "function": "something",
                "generated_test_path": "tests/test_undisclosed.py",
                "status": "generated",
            },
        }

    orchestrator.register("pre-commit", fake_undisclosed_test_maintenance)
    orchestrator.register("pre-commit", reliability.run)

    results = orchestrator.dispatch("pre-commit", target=str(tmp_path))

    rel_result = results[1]
    assert rel_result["details"]["classification"] == "reliable"
    assert rel_result["details"]["is_compliant"] is False
    assert rel_result["passed"] is False
