from pathlib import Path

from ai_test_tool.agents import test_maintenance

TRIP_LOGIC_SOURCE = '''
from datetime import date


def trip_duration_days(start_date: date, end_date: date) -> int:
    return (end_date - start_date).days + 1


def is_day_within_trip(day: date, start_date: date, end_date: date) -> bool:
    return start_date <= day <= end_date


def trips_overlap(start_a: date, end_a: date, start_b: date, end_b: date) -> bool:
    return start_a <= end_b and start_b <= end_a
'''

EXISTING_TEST_SOURCE = '''
from datetime import date

import pytest

from app.trip_logic import is_day_within_trip, trip_duration_days


def test_trip_duration_days_single_day():
    d = date(2026, 1, 1)
    assert trip_duration_days(d, d) == 1


def test_is_day_within_trip_true_for_a_day_inside_range():
    assert is_day_within_trip(date(2026, 1, 3), date(2026, 1, 1), date(2026, 1, 5))
'''


def _seed_repo(tmp_path: Path, test_source: str = EXISTING_TEST_SOURCE) -> Path:
    (tmp_path / "app").mkdir()
    (tmp_path / "app" / "trip_logic.py").write_text(TRIP_LOGIC_SOURCE, encoding="utf-8")
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "test_trip_logic.py").write_text(test_source, encoding="utf-8")
    return tmp_path


def test_run_reports_skipped_when_target_file_missing(tmp_path: Path):
    result = test_maintenance.run(target=str(tmp_path), stage="pre-commit")

    assert result["passed"] is False
    assert result["details"]["status"] == "skipped"


def test_run_generates_tests_when_trips_overlap_is_untested(tmp_path: Path):
    _seed_repo(tmp_path)

    result = test_maintenance.run(target=str(tmp_path), stage="pre-commit")

    assert result["details"]["status"] == "generated"
    assert result["details"]["generated_test_path"] is not None

    test_file = tmp_path / "tests" / "test_trip_logic.py"
    content = test_file.read_text(encoding="utf-8")
    assert "trips_overlap" in content
    assert "AI-generated by ai-test-tool" in content


def test_run_is_idempotent_on_second_call(tmp_path: Path):
    _seed_repo(tmp_path)

    first = test_maintenance.run(target=str(tmp_path), stage="pre-commit")
    second = test_maintenance.run(target=str(tmp_path), stage="pre-commit")

    assert first["details"]["status"] == "generated"
    assert second["details"]["status"] == "no_change_needed"


def test_run_generated_tests_are_syntactically_valid_and_pass(tmp_path: Path):
    import subprocess
    import sys

    _seed_repo(tmp_path)
    test_maintenance.run(target=str(tmp_path), stage="pre-commit")

    (tmp_path / "app" / "__init__.py").write_text("", encoding="utf-8")
    (tmp_path / "tests" / "__init__.py").write_text("", encoding="utf-8")

    result = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "tests/test_trip_logic.py"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_run_does_not_touch_trips_overlap_when_already_tested(tmp_path: Path):
    already_tested_source = EXISTING_TEST_SOURCE.replace(
        "from app.trip_logic import is_day_within_trip, trip_duration_days",
        "from app.trip_logic import is_day_within_trip, trip_duration_days, trips_overlap",
    )
    _seed_repo(tmp_path, test_source=already_tested_source)
    original_content = (tmp_path / "tests" / "test_trip_logic.py").read_text(encoding="utf-8")

    result = test_maintenance.run(target=str(tmp_path), stage="pre-commit")

    assert result["details"]["status"] == "no_change_needed"
    unchanged_content = (tmp_path / "tests" / "test_trip_logic.py").read_text(encoding="utf-8")
    assert unchanged_content == original_content


def test_run_reports_other_untested_functions_as_gaps(tmp_path: Path):
    # EXISTING_TEST_SOURCE only tests two of trip_logic's three functions —
    # trip_duration_days and is_day_within_trip are covered, trips_overlap
    # is not (that's the one this agent generates for). Adding a fourth,
    # genuinely untested function to prove gaps beyond trips_overlap are
    # reported too, not silently dropped.
    trip_logic_with_extra_function = TRIP_LOGIC_SOURCE + (
        "\n\ndef trip_cost_per_day(total_cost: float, days: int) -> float:\n"
        "    return total_cost / days\n"
    )
    _seed_repo(tmp_path)
    (tmp_path / "app" / "trip_logic.py").write_text(trip_logic_with_extra_function, encoding="utf-8")

    result = test_maintenance.run(target=str(tmp_path), stage="pre-commit")

    assert "trip_cost_per_day" in result["details"]["other_coverage_gaps"]
    assert "trip_cost_per_day" in result["summary"]
