import subprocess
import sys
from pathlib import Path

import pytest

from ai_test_tool import ai_client
from ai_test_tool.agents import test_maintenance

GENERATED_TEST = '''def test_trips_overlap_true_for_touching_ranges():
    from datetime import date
    assert trips_overlap(date(2026, 1, 1), date(2026, 1, 5), date(2026, 1, 5), date(2026, 1, 7))


def test_trips_overlap_false_for_disjoint_ranges():
    from datetime import date
    assert not trips_overlap(date(2026, 1, 1), date(2026, 1, 2), date(2026, 1, 5), date(2026, 1, 7))
'''


def _init_repo(tmp_path: Path) -> Path:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=tmp_path, check=True)
    return tmp_path


def _seed_source(tmp_path: Path) -> Path:
    app_dir = tmp_path / "app"
    app_dir.mkdir()
    (app_dir / "__init__.py").write_text("", encoding="utf-8")
    source = app_dir / "trip_logic.py"
    source.write_text(
        "from datetime import date\n\n\n"
        "def trip_duration_days(start_date: date, end_date: date) -> int:\n"
        "    return (end_date - start_date).days + 1\n\n\n"
        "def trips_overlap(start_a: date, end_a: date, start_b: date, end_b: date) -> bool:\n"
        "    return start_a <= end_b and start_b <= end_a\n\n\n"
        "def _internal_helper(x):\n"
        "    return x\n",
        encoding="utf-8",
    )
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "__init__.py").write_text("", encoding="utf-8")
    return source


def _stage(repo: Path, *paths: Path) -> None:
    subprocess.run(["git", "add", *[str(p) for p in paths]], cwd=repo, check=True)


def test_run_reports_nothing_to_scan_with_no_changed_files(tmp_path: Path):
    _init_repo(tmp_path)

    result = test_maintenance.run(target=str(tmp_path), stage="pre-commit")

    assert result["passed"] is True
    assert result["details"]["generated"] == []


def test_run_generates_tests_for_untested_functions_via_ai(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    source = _seed_source(repo)
    _stage(repo, source)

    monkeypatch.setattr(ai_client, "generate", lambda prompt, **k: GENERATED_TEST)

    result = test_maintenance.run(target=str(repo), stage="pre-commit")

    generated = result["details"]["generated"]
    assert {g["function"] for g in generated} == {"trip_duration_days", "trips_overlap"}
    assert [Path(p).as_posix() for p in result["details"]["generated_test_paths"]] == [
        "tests/test_trip_logic.py"
    ]

    test_content = (repo / "tests" / "test_trip_logic.py").read_text(encoding="utf-8")
    assert "AI-generated by ai-test-tool" in test_content
    assert "trips_overlap" in test_content


def test_run_never_generates_for_private_helpers(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    source = _seed_source(repo)
    _stage(repo, source)
    monkeypatch.setattr(ai_client, "generate", lambda prompt, **k: GENERATED_TEST)

    result = test_maintenance.run(target=str(repo), stage="pre-commit")

    functions = {g["function"] for g in result["details"]["generated"]}
    assert "_internal_helper" not in functions
    assert not any("_internal_helper" in gap for gap in result["details"]["coverage_gaps"])


def test_run_skips_functions_already_covered_by_an_import(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    source = _seed_source(repo)
    (repo / "tests" / "test_trip_logic.py").write_text(
        "from app.trip_logic import trip_duration_days\n\n\n"
        "def test_trip_duration_days_single_day():\n"
        "    from datetime import date\n"
        "    d = date(2026, 1, 1)\n"
        "    assert trip_duration_days(d, d) == 1\n",
        encoding="utf-8",
    )
    _stage(repo, source)
    monkeypatch.setattr(ai_client, "generate", lambda prompt, **k: GENERATED_TEST)

    result = test_maintenance.run(target=str(repo), stage="pre-commit")

    functions = {g["function"] for g in result["details"]["generated"]}
    assert functions == {"trips_overlap"}
    assert "trip_duration_days" not in functions


def test_run_skips_gracefully_when_ai_is_unavailable(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    source = _seed_source(repo)
    _stage(repo, source)

    def _raise(prompt, **k):
        raise ai_client.AIUnavailable("ANTHROPIC_API_KEY is not set")

    monkeypatch.setattr(ai_client, "generate", _raise)

    result = test_maintenance.run(target=str(repo), stage="pre-commit")

    assert result["details"]["generated"] == []
    assert result["passed"] is False
    assert len(result["details"]["skipped"]) == 2
    assert all("ANTHROPIC_API_KEY" in s["reason"] for s in result["details"]["skipped"])
    # The repo itself must be untouched — no partial/empty test file created.
    assert not (repo / "tests" / "test_trip_logic.py").exists()


def test_run_respects_the_per_run_generation_cap(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    app_dir = repo / "app"
    app_dir.mkdir()
    (app_dir / "__init__.py").write_text("", encoding="utf-8")
    lots_of_functions = "\n\n".join(f"def f{i}():\n    return {i}" for i in range(8))
    source = app_dir / "many.py"
    source.write_text(lots_of_functions + "\n", encoding="utf-8")
    (repo / "tests").mkdir()
    _stage(repo, source)

    calls = []
    monkeypatch.setattr(
        ai_client, "generate", lambda prompt, **k: calls.append(1) or "def test_x():\n    assert True\n"
    )

    result = test_maintenance.run(target=str(repo), stage="pre-commit")

    assert len(calls) == test_maintenance.MAX_FUNCTIONS_PER_RUN
    assert len(result["details"]["generated"]) == test_maintenance.MAX_FUNCTIONS_PER_RUN
    assert len(result["details"]["coverage_gaps"]) == 8


def test_on_save_scopes_to_only_the_saved_file(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    app_dir = repo / "app"
    app_dir.mkdir()
    (app_dir / "__init__.py").write_text("", encoding="utf-8")
    (app_dir / "a.py").write_text("def a():\n    return 1\n", encoding="utf-8")
    (app_dir / "b.py").write_text("def b():\n    return 2\n", encoding="utf-8")
    (repo / "tests").mkdir()

    monkeypatch.setattr(ai_client, "generate", lambda prompt, **k: "def test_a():\n    assert a() == 1\n")

    result = test_maintenance.run(
        target=str(repo), stage="on-save", changed_file=str(app_dir / "a.py")
    )

    functions = {g["function"] for g in result["details"]["generated"]}
    assert functions == {"a"}
    assert not (repo / "tests" / "test_b.py").exists()


def test_generated_tests_strip_markdown_fences(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    source = _seed_source(repo)
    _stage(repo, source)

    fenced = "```python\n" + GENERATED_TEST + "```"
    monkeypatch.setattr(ai_client, "generate", lambda prompt, **k: fenced)

    test_maintenance.run(target=str(repo), stage="pre-commit")

    content = (repo / "tests" / "test_trip_logic.py").read_text(encoding="utf-8")
    assert "```" not in content


def test_run_redacts_secrets_before_they_reach_the_ai_prompt(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    app_dir = repo / "app"
    app_dir.mkdir()
    (app_dir / "__init__.py").write_text("", encoding="utf-8")
    source = app_dir / "config.py"
    source.write_text(
        "def get_headers():\n"
        '    api_key = "sk-live-abcdef123456"\n'
        '    return {"Authorization": f"Bearer {api_key}"}\n',
        encoding="utf-8",
    )
    (repo / "tests").mkdir()
    _stage(repo, source)

    captured_prompts = []

    def _fake_generate(prompt, **k):
        captured_prompts.append(prompt)
        return "def test_get_headers():\n    assert 'Authorization' in get_headers()\n"

    monkeypatch.setattr(ai_client, "generate", _fake_generate)

    result = test_maintenance.run(target=str(repo), stage="pre-commit")

    assert "sk-live-abcdef123456" not in captured_prompts[0]
    assert all("sk-live-abcdef123456" not in p for p in captured_prompts)
    assert result["details"]["generated"][0]["secrets_redacted"] is True
    assert "secrets redacted" in result["summary"]


def test_generated_tests_are_syntactically_valid_and_pass(tmp_path: Path, monkeypatch):
    repo = _init_repo(tmp_path)
    source = _seed_source(repo)
    _stage(repo, source)
    monkeypatch.setattr(ai_client, "generate", lambda prompt, **k: GENERATED_TEST)

    test_maintenance.run(target=str(repo), stage="pre-commit")

    result = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "tests/test_trip_logic.py"],
        cwd=repo,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr
